services:
 
  db:
    image: postgres:15.3
    restart: always
    ports:
    - "5433:5432"  
    environment:
      POSTGRES_USER: ademir_serralheria
      POSTGRES_PASSWORD: SenhaForte@123
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata: